name: CI
on:
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/ci.yml
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: harupy/find-trailing-whitespace@v1.0

  linux:
    name: linux (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - swift: swift:5.3
          name: 5.3
        - swift: swift:5.4
          name: 5.4
        - swift: swiftlang/swift:nightly-5.5
          name: 5.5
    container:
      image: ${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-code-coverage --parallel --enable-test-discovery

    - name: Generate Coverage Report
      run: |
        apt-get -qq update
        apt-get -qq install curl  # for codecov action 🙄
        b=$(swift build --show-bin-path)
        llvm-cov export \
          -format lcov \
          -instr-profile="$b"/codecov/default.profdata \
          --ignore-filename-regex='\.build/' \
          "$b"/*.xctest \
          > info.lcov
    - uses: codecov/codecov-action@v1
      with:
        file: ./info.lcov

  apple:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
          - tvOS
          - iOS
          - watchOS
        swift:
          - 5.3
          - 5.4
          - 5.5
    name: ${{ matrix.platform }} (${{ matrix.swift }})
    steps:
    - uses: actions/checkout@v2
    - run: |
        cd Tests/A+/JavaScript
        npm ci
        npm run build
      if: ${{ matrix.platform == 'macOS' }}
    - uses: mxcl/xcodebuild@v1
      with:
        swift: ${{ matrix.swift }}
        platform: ${{ matrix.platform }}
        code-coverage: true
        warnings-as-errors: true
      continue-on-error: ${{ matrix.swift == '5.5' }}
    - uses: codecov/codecov-action@v1

  windows:
    runs-on: windows-latest
    steps:
      - uses: seanmiddleditch/gha-setup-vsdevenv@v3
      - uses: mxcl/setup-swift@v1
      - uses: actions/checkout@v2
      - run: swift test --parallel